In [1]:
## Test Team Formation framework with Freelancer Data
## Balancing Task Coverage vs. Maximum Expert Load
## Karan Vombatkere, Dec 2021

import numpy as np
import pandas as pd
import time

#Set logging level
import TeamFormationProblem as TFP

In [2]:
#Preliminary Testing
task_list = [['s1', 's2', 's4', 's5'], ['s3', 's2'], ['s1', 's3', 's5'], ['s2', 's4'],['s1', 's4', 's5'], ['s3'], ['s1', 's5'], ['s2', 's4']]
expert_list = [['s2', 's3'], ['s2', 's4'], ['s3'], ['s5', 's4']]

In [3]:
teamFormationTest = TFP.TeamFormationProblem(task_list, expert_list)
teamFormationTest.computeTaskAssigment()

2021-12-20 16:45:27,020 |INFO: Team Formation Problem initialized with 8 tasks and 4 experts
2021-12-20 16:45:27,022 |INFO: --------------------------------------------------------------------------------------------------
2021-12-20 16:45:27,022 |INFO: Computing Greedy Task Assignment for threshold max load, T_i=1
2021-12-20 16:45:27,023 |INFO: Expert Index List: [0, 1, 2, 3]
2021-12-20 16:45:27,025 |INFO: Greedy Task Assignment = 
[[0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0 0]]
2021-12-20 16:45:27,026 |INFO: F_i = 2.667
2021-12-20 16:45:27,026 |INFO: --------------------------------------------------------------------------------------------------
2021-12-20 16:45:27,027 |INFO: Computing Greedy Task Assignment for threshold max load, T_i=2
2021-12-20 16:45:27,028 |INFO: Expert Index List: [0, 1, 2, 3, 0, 1, 2, 3]
2021-12-20 16:45:27,031 |INFO: Greedy Task Assignment = 
[[0 1 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 1]
 [0 0 0 0 0 1 0 0]
 [1 0 0 0 1 0 0 0]]
2021-12-20

In [4]:
#Import Freelancer data
#Freelancer from DropBox link: https://www.dropbox.com/sh/8zpsi1etvvvvj5k/AAD-J9ZQmSsbnSmEILBMD9uxa/datasets/real?dl=0&subfolder_nav_tracking=1
#freelance_experts.csv and freelance_projects.csv

def extract_skills(row):
    skills = []
    for i,val in enumerate(row):
        if val == 1:
            skills+=str(i)
    return skills            

    
def importFreelancerData(experts_filename='../Datasets/freelance_experts.csv', tasks_filename='../Datasets/freelance_projects.csv'):
    #Extract tasks skills as list
    freelance_tasks_df = pd.read_csv(tasks_filename, header=None)
    freelance_tasks_df['Task_Skills'] = freelance_tasks_df.apply(lambda row: extract_skills(row), axis=1)
    task_skills_list = freelance_tasks_df.Task_Skills.to_list()
    
    #Extract experts skills as list
    freelance_experts_df = pd.read_csv(experts_filename, header=None)
    freelance_experts_df['Expert_Skills'] = freelance_experts_df.apply(lambda row: extract_skills(row), axis=1)
    expert_skills_list = freelance_experts_df.Expert_Skills.to_list()

    return task_skills_list, expert_skills_list
    

In [5]:
t,e = importFreelancerData()

In [6]:
FreelancerTest = TFP.TeamFormationProblem(t[0:50], e[0:60], max_workload_threshold=1)

2021-12-20 16:45:27,333 |INFO: Team Formation Problem initialized with 50 tasks and 60 experts


In [7]:
FreelancerTest.computeTaskAssigment()

2021-12-20 16:45:27,414 |INFO: --------------------------------------------------------------------------------------------------
2021-12-20 16:45:27,418 |INFO: Computing Greedy Task Assignment for threshold max load, T_i=1
2021-12-20 16:45:27,418 |INFO: Expert Index List: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]
2021-12-20 16:45:32,284 |INFO: Greedy Task Assignment = 
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
2021-12-20 16:45:32,289 |INFO: F_i = 34.190
2021-12-20 16:45:32,290 |INFO: Best Task Assignment is for max workload threshold: 1, F_i(max)=34.190 
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
2021-12-20 16:45:32,290 |INFO: 
Total Computation t

In [8]:
FreelancerTest.displayTaskAssignment(FreelancerTest.taskAssignment)

Experts Assigned to Task 0: [47]
Experts Assigned to Task 1: [32]
Experts Assigned to Task 2: [12]
Experts Assigned to Task 3: [6]
Experts Assigned to Task 4: [41]
Experts Assigned to Task 5: [31, 57]
Experts Assigned to Task 6: [28]
Experts Assigned to Task 7: [37, 44]
Experts Assigned to Task 8: [26]
Experts Assigned to Task 9: [14, 52]
Experts Assigned to Task 10: [56]
Experts Assigned to Task 11: [53]
Experts Assigned to Task 12: [8]
Experts Assigned to Task 13: [20, 24]
Experts Assigned to Task 14: [35, 36]
Experts Assigned to Task 15: [11, 49]
Experts Assigned to Task 16: [45]
Experts Assigned to Task 17: [9]
Experts Assigned to Task 18: [15]
Experts Assigned to Task 19: [38, 48]
Experts Assigned to Task 20: [29, 40]
Experts Assigned to Task 21: [2]
Experts Assigned to Task 22: [4]
Experts Assigned to Task 23: [25]
Experts Assigned to Task 24: [34]
Experts Assigned to Task 25: [13, 59]
Experts Assigned to Task 26: [18]
Experts Assigned to Task 27: [42, 55]
Experts Assigned to Tas